# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

In [2]:
import torch
import numpy as np

# Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:



**Directly from data**


Tensors can be created directly from data. The data type is automatically inferred.

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

**From Numpy Arrays**

In [4]:
data = [[1, 2],[3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

**From another tensor:**


The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor : {x_ones}")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f"Rand Tensor : {x_rand}")

Ones Tensor : tensor([[1, 1],
        [1, 1]])
Rand Tensor : tensor([[0.9231, 0.0695],
        [0.5461, 0.8302]])


**With random or constant values:**


"*shape*" is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [6]:
shape = (3,4)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7055, 0.6184, 0.3681, 0.8862],
        [0.1047, 0.2932, 0.7549, 0.3610],
        [0.0844, 0.2654, 0.9197, 0.8630]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


# Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [7]:
tensor1 = torch.rand((3,4))
print(f"Shape of the Tensor is : {tensor1.shape}")
print(f"Data-Type of the Tensor is  : {tensor1.dtype}")
print(f"Device on which Tensor Stored : {tensor1.device}")

Shape of the Tensor is : torch.Size([3, 4])
Data-Type of the Tensor is  : torch.float32
Device on which Tensor Stored : cpu


# Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described here.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [8]:
if torch.cuda.is_available():
  tensor1.to('cuda')

In [9]:
tensor = torch.rand((4,4))
print(tensor)

tensor([[0.0654, 0.0247, 0.1681, 0.0601],
        [0.6868, 0.8884, 0.0983, 0.1213],
        [0.3658, 0.2034, 0.3875, 0.0372],
        [0.8083, 0.0651, 0.0968, 0.6325]])


### Standard numpy-like indexing and slicing:

In [10]:
print("Frist Row : ",tensor[0,:])
print("Second Row : ",tensor[1,:])
print("Third Row : ",tensor[2,:])
print("Fourth Row : ",tensor[3,:])

Frist Row :  tensor([0.0654, 0.0247, 0.1681, 0.0601])
Second Row :  tensor([0.6868, 0.8884, 0.0983, 0.1213])
Third Row :  tensor([0.3658, 0.2034, 0.3875, 0.0372])
Fourth Row :  tensor([0.8083, 0.0651, 0.0968, 0.6325])


In [11]:
print("First Column : ",tensor[:,0])
print("Second Column : ",tensor[:,1])
print("Third Column : ",tensor[:,2])
print("Fourth Column : ",tensor[:,3])

First Column :  tensor([0.0654, 0.6868, 0.3658, 0.8083])
Second Column :  tensor([0.0247, 0.8884, 0.2034, 0.0651])
Third Column :  tensor([0.1681, 0.0983, 0.3875, 0.0968])
Fourth Column :  tensor([0.0601, 0.1213, 0.0372, 0.6325])


In [12]:
print("Matrix in between : ",tensor[1:3,1:3])

Matrix in between :  tensor([[0.8884, 0.0983],
        [0.2034, 0.3875]])


**Joining tensors** 

We can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining op that is subtly different from torch.cat.

In [13]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1.shape)


torch.Size([12, 4])


In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1.shape)

torch.Size([4, 12])


### Airthematic Operations

**Multiplication of Matrix**

In [20]:
x1 = torch.rand((2,3))
x1

tensor([[0.9793, 0.4771, 0.4542],
        [0.8887, 0.5077, 0.8775]])

In [23]:
x2 = torch.rand((3,2))
x2

tensor([[0.0858, 0.8664],
        [0.3538, 0.0625],
        [0.1238, 0.3449]])

Matrix Multiplication can be done in two ways :
1. **Using Matmul Method**
2. **Using @**

In [24]:
# Using Matmul Method
x1.matmul(x2)

tensor([[0.3090, 1.0350],
        [0.3645, 1.1043]])

In [25]:
# Using @ Symbol
x1 @ x2

tensor([[0.3090, 1.0350],
        [0.3645, 1.1043]])

**Single-element tensors** If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using **item():**

In [27]:
x1.sum()
print(f"The sum of X1 : {x1.sum()} and type is : {type(x1.sum())}")
print(f"The sum of X1 : {x1.sum().item()} and type is : {type(x1.sum().item())}")

The sum of X1 : 4.184497833251953 and type is : <class 'torch.Tensor'>
The sum of X1 : 4.184497833251953 and type is : <class 'float'>
